---
- name: configure shell environment for current user
  hosts: all
  gather_facts: yes
  tags: shell
  vars:
    desired_shell: /bin/zsh
  tasks:
    - name: "set current user shell to {{ desired_shell }}"
      become: yes
      user:
        name: "{{ ansible_user_id }}"
        shell: "{{ desired_shell }}"

- name: dotfiles
  hosts: all
  gather_facts: yes
  tags: dotfiles
  tasks:
    # my dotfiles rely upon antigen to manage shell plugins, so make sure it is
    # installed and ready for our usage!
    - name: install antigen
      homebrew: name=antigen state=present

    # whereas the dotfiles themselves are stored and synced via homeshick,
    # so install that as well.
    #
    # NOTE: I personally don't love that homeshick tool itself is managed as a
    # git repo, and self-updated that way (I'd prefer a binary style tool that
    # doesn't need to be sourced), but it's the best for my usage I've found
    # currently.
    - name: homeshick | clone homeshick
      git:  repo=https://github.com/andsens/homeshick.git
            dest=~/.homesick/repos/homeshick
            update=no

    - name: homeshick | dotfiles cloned
      git:  repo=https://github.com/{{ ansible_user_id }}/dotfiles.git
            dest=~/.homesick/repos/dotfiles
            update=no
      register: dotfiles_cloned

    - name: homeshick | dotfiles force link if just first installed
      when: dotfiles_cloned is changed
      command: ~/.homesick/repos/homeshick/bin/homeshick link dotfiles --force

- name: xtra placeholder (prevents error condition on --skip-tags=xtra)
  hosts: all
  gather_facts: no
  tags: xtra
  tasks:
    - debug: msg="nothing to see here, move along"
