---
- name: Go Development Environment
  hosts: all
  tags: go
  vars:
    gopath: ~/src/go

  tasks:
    - name: install Go platform
      homebrew: name=go state=present

    - name: install tools needed for `go get` to function as expected
      homebrew:
        state: present
        name:
          - git
          - hg
          - bzr  

    - name: install brew managed Go tooling
      homebrew:
        state: present
        name:
          - golangci/tap/golangci-lint
          - goreleaser/tap/goreleaser

    - name: install additional Go tools
      command: go get {{ item }}
      environment:
        GOPATH:  "{{ gopath | expanduser }}"
      args:
        creates: "{{ gopath | expanduser }}/src/{{ item }}/"
      with_items:
        - golang.org/x/perf/cmd/benchstat
        - github.com/ajstarks/svgo/benchviz
        - github.com/oligot/go-mod-upgrade
