---
# For the most part, I primarily would do any Ruby development within a Docker
# container these days to handle versioning easier.
#
# So this playbook is now changed to basically just get rid of anything else
# and install bundler into global gems for system ruby.
- name: Ruby Development Environment
  hosts: all
  tags: ruby
  vars:
    default_gems:
      - bundler

  tasks:
    - name: dont use homebrew ruby
      homebrew: name=ruby state=absent

    - name: install desired global RubyGems
      gem:
        name: "{{ item }}"
        state: present
        user_install: no
        executable: '/usr/bin/gem' # make sure we use system version
      with_items: "{{ default_gems }}"
